### ISSUE TITLE
`Array` nodes should have a `__repr__`

### ISSUE THREAD

**Issue by inducer** [inducer/pytato#165]
(Possibly also a `__str__`?)

Not having a meaningful print syntax makes debugging code kind of a pain. We'll have to figure out how much of the DAG to actually print. We probably want a `StringifyMapper` (or some such) that's somewhat customizable, to use as the basis of this functionality.

cc @kaushikcfd

**Comment by matthiasdiener** [comment]
As a side note, this package might be interesting to print a dag to the console: https://github.com/sambrightman/asciidag

**Comment by kaushikcfd** [comment]
I very much like the approach taken by pymbolic. `__repr__` is something that could be be used to put in a `REPL` to reproduce the expression, but I'm not sure it will be helpful for debugging because the size of the expressions will quickly get out of hand (or even mutliple hands for that matter :p). And `__str__` could be something for similar to an array expression, probably could be left unimplemented for non-standard IndexLambdas.

>  https://github.com/sambrightman/asciidag

Thanks! This is also very convenient to have in certain cases.
